### ISSUE TITLE
Test suite on toy corpora

### ISSUE THREAD

**Issue by fauxneticien** [CoEDL/kaldi_helpers#25]
@benfoley — did you set 'Phrase' as the default tier name setting for `_run-elan`?

This causes `abui_toy_corpus` to die on `task _run-elan`, see lines [463](https://travis-ci.org/CoEDL/kaldi-helpers/jobs/339785194#L463) and [472](https://travis-ci.org/CoEDL/kaldi-helpers/jobs/339785194#L472) in this build log.

**Comment by benfoley** [comment]
I've updated the tier names in the toy corpus. Can you run the test again?

**Comment by fauxneticien** [comment]
Passes (for) now: https://travis-ci.org/CoEDL/kaldi-helpers/builds/340025899
